import { COMPOSER_PLACEHOLDER_TEXT_CLASS_NAME } from "~/components/chat/composerPickerStyles";
import { cn } from "~/lib/utils";

const ENVIRONMENT_PANEL_LABEL_CLASS_NAME = cn("font-normal", COMPOSER_PLACEHOLDER_TEXT_CLASS_NAME);

export const ENVIRONMENT_PANEL_TITLE_CLASS_NAME = cn(ENVIRONMENT_PANEL_LABEL_CLASS_NAME, "text-ui");

export const ENVIRONMENT_PANEL_SECTION_LABEL_INLINE_CLASS_NAME = cn(
  ENVIRONMENT_PANEL_LABEL_CLASS_NAME,
  "text-ui-sm",
);

export const ENVIRONMENT_PANEL_SECTION_LABEL_CLASS_NAME = cn(
  ENVIRONMENT_PANEL_SECTION_LABEL_INLINE_CLASS_NAME,
  "px-2 py-1",
);
