export const DESKTOP_IPC_CHANNELS = {
  pickFolder: "desktop:pick-folder",
  saveFile: "desktop:save-file",
  confirm: "desktop:confirm",
  setTheme: "desktop:set-theme",
  windowMaterialGetState: "desktop:window-material-get-state",
  windowMaterialSetEnabled: "desktop:window-material-set-enabled",
  getAppIcon: "desktop:get-app-icon",
  setAppIcon: "desktop:set-app-icon",
  contextMenu: "desktop:context-menu",
  openExternal: "desktop:open-external",
  showInFolder: "desktop:show-in-folder",
  clipboardReadFiles: "desktop:clipboard-read-files",
  clipboardWriteImage: "desktop:clipboard-write-image",
  windowMinimize: "desktop:window-minimize",
  windowToggleMaximize: "desktop:window-toggle-maximize",
  windowClose: "desktop:window-close",
  windowGetState: "desktop:window-get-state",
  windowState: "desktop:window-state",
  customTitleBarGetState: "desktop:custom-title-bar-get-state",
  customTitleBarSetPreference: "desktop:custom-title-bar-set-preference",
  customTitleBarRelaunch: "desktop:custom-title-bar-relaunch",
  setMenuShortcuts: "desktop:set-menu-shortcuts",
  menuAction: "desktop:menu-action",
  quitConfirmationRequest: "desktop:quit-confirmation-request",
  quitConfirmationResponse: "desktop:quit-confirmation-response",
  updateState: "desktop:update-state",
  updateGetState: "desktop:update-get-state",
  updateCheck: "desktop:update-check",
  updateDownload: "desktop:update-download",
  updateInstall: "desktop:update-install",
  notificationsGetPermission: "desktop:notifications-get-permission",
  notificationsRequestPermission: "desktop:notifications-request-permission",
  notificationsOpenSettings: "desktop:notifications-open-settings",
  notificationsIsSupported: "desktop:notifications-is-supported",
  notificationsShow: "desktop:notifications-show",
  zoomFactor: "desktop:zoom-factor",
  zoomFactorChanged: "desktop:zoom-factor-changed",
  wsUrl: "desktop:get-ws-url",
  transcribeVoice: "desktop:server-transcribe-voice",
} as const;

export const SERVER_TRANSCRIBE_VOICE_CHANNEL = DESKTOP_IPC_CHANNELS.transcribeVoice;
