import { createBackendReadinessCoordinator } from "../backend/backendReadinessCoordinator";
import { createBackendSupervisor } from "../backend/backendSupervisor";
import { createDesktopBrowserServices } from "../browser/desktopBrowserServices";
import { createDesktopComputerSetup } from "../computer/desktopComputerSetup";
import { getSafeExternalUrl, getSafeTheme, isSaveFileInput } from "../main/ipc/ipcValidation";
import { createRegisterDesktopIpc } from "../main/ipc/registerDesktopIpc";
import { createBundleSwapWatcher } from "../main/lifecycle/bundleSwapWatcher";
import { createDesktopBootstrap } from "../main/lifecycle/desktopBootstrap";
import { createDesktopLogging } from "../main/lifecycle/desktopLogging";
import { createDesktopResources } from "../main/lifecycle/desktopResources";
import { createDesktopShutdown } from "../main/lifecycle/desktopShutdown";
import { createRendererRecovery } from "../main/lifecycle/rendererRecovery";
import { createAutoUpdater } from "../main/updates/autoUpdater";
import { createInstallRecovery } from "../main/updates/installRecovery";
import { createUpdateActivity } from "../main/updates/updateActivity";
import { createUpdateCache } from "../main/updates/updateCache";
import { createUpdateDownload } from "../main/updates/updateDownload";
import { createUpdateInstall } from "../main/updates/updateInstall";
import { createAppIdentity } from "../main/window/appIdentity";
import { createApplicationMenu } from "../main/window/applicationMenu";
import { createContextMenuIcons } from "../main/window/contextMenuIcons";
import { createDesktopNotifications } from "../main/window/desktopNotifications";
import { createMainWindow } from "../main/window/mainWindow";
import { createMediaPermissionHandlers } from "../main/window/mediaPermissionHandlers";
import { createDesktopRecoveryCoordinator } from "../storage/desktopRecoveryCoordinator";
import { createSchemaRecovery } from "../storage/schemaRecovery";
import type { DesktopRuntime } from "./desktopRuntimeTypes";
import { initializeDesktopState } from "./initializeDesktopState";
import { registerDesktopLifecycle } from "./lifecycle/registerDesktopLifecycle";
export function startDesktopApplication(): void {
  // Install callable services before evaluating state, preserving main's function hoisting.
  const desktopRuntime = {} as DesktopRuntime;
  Object.assign(desktopRuntime, createDesktopBrowserServices(desktopRuntime));
  Object.assign(desktopRuntime, createDesktopLogging(desktopRuntime));
  Object.assign(desktopRuntime, { getSafeExternalUrl, getSafeTheme, isSaveFileInput });
  Object.assign(desktopRuntime, createBackendReadinessCoordinator(desktopRuntime));
  Object.assign(desktopRuntime, createContextMenuIcons(desktopRuntime));
  Object.assign(desktopRuntime, createInstallRecovery(desktopRuntime));
  Object.assign(desktopRuntime, createDesktopResources(desktopRuntime));
  Object.assign(desktopRuntime, createDesktopRecoveryCoordinator(desktopRuntime));
  Object.assign(desktopRuntime, createApplicationMenu(desktopRuntime));
  Object.assign(desktopRuntime, createDesktopComputerSetup(desktopRuntime));
  Object.assign(desktopRuntime, createDesktopNotifications(desktopRuntime));
  Object.assign(desktopRuntime, createAppIdentity(desktopRuntime));
  Object.assign(desktopRuntime, createBundleSwapWatcher(desktopRuntime));
  Object.assign(desktopRuntime, createUpdateCache(desktopRuntime));
  Object.assign(desktopRuntime, createUpdateActivity(desktopRuntime));
  Object.assign(desktopRuntime, createUpdateDownload(desktopRuntime));
  Object.assign(desktopRuntime, createUpdateInstall(desktopRuntime));
  Object.assign(desktopRuntime, createAutoUpdater(desktopRuntime));
  Object.assign(desktopRuntime, createBackendSupervisor(desktopRuntime));
  Object.assign(desktopRuntime, createSchemaRecovery(desktopRuntime));
  Object.assign(desktopRuntime, createDesktopShutdown(desktopRuntime));
  Object.assign(desktopRuntime, createRegisterDesktopIpc(desktopRuntime));
  Object.assign(desktopRuntime, createMainWindow(desktopRuntime));
  Object.assign(desktopRuntime, createRendererRecovery(desktopRuntime));
  Object.assign(desktopRuntime, createMediaPermissionHandlers(desktopRuntime));
  Object.assign(desktopRuntime, createDesktopBootstrap(desktopRuntime));
  initializeDesktopState(desktopRuntime);
  registerDesktopLifecycle(desktopRuntime);
}
