import { type CuaComputerTask } from "@glade/shared/computer/cuaDriverProtocol";
import { type Socket } from "node:net";
import { createCuaDesktopAdmission } from "./cuaDesktopAdmission";
import { createCuaDriverGeneration } from "./cuaDriverGeneration";
import { createCuaHostDispatch } from "./cuaHostDispatch";
import { ControlledTarget, TaskRequest } from "./cuaHostPolicy";
import { type CuaDriverHostOptions, type CuaHostRuntime } from "./cuaHostRuntimeTypes";
import { createCuaHostTransport } from "./cuaHostTransport";
import { createCuaInputInterruption } from "./cuaInputInterruption";
import { createCuaTargetObservation } from "./cuaTargetObservation";
import { createCuaTaskCursors } from "./cuaTaskCursors";
import { createCuaTaskExecution } from "./cuaTaskExecution";

export function createCuaHostRuntime(options: CuaDriverHostOptions): CuaHostRuntime {
  // Assemble callable operations before resources can invoke their callbacks.
  const hostRuntime = {} as { -readonly [Key in keyof CuaHostRuntime]: CuaHostRuntime[Key] };
  Object.assign(hostRuntime, createCuaHostTransport(hostRuntime));
  Object.assign(hostRuntime, createCuaHostDispatch(hostRuntime));
  Object.assign(hostRuntime, createCuaTaskExecution(hostRuntime));
  Object.assign(hostRuntime, createCuaTaskCursors(hostRuntime));
  Object.assign(hostRuntime, createCuaDriverGeneration(hostRuntime));
  Object.assign(hostRuntime, createCuaInputInterruption(hostRuntime));
  Object.assign(hostRuntime, createCuaTargetObservation(hostRuntime));
  Object.assign(hostRuntime, createCuaDesktopAdmission(hostRuntime));
  hostRuntime.directory = "";
  hostRuntime.server = undefined;
  hostRuntime.generation = undefined;
  hostRuntime.starting = undefined;
  hostRuntime.retiring = Promise.resolve();
  hostRuntime.closed = false;
  hostRuntime.suspended = false;
  hostRuntime.inputMonitorArmed = false;
  hostRuntime.inputMonitorRequested = false;
  hostRuntime.nativeInputCleanupPending = undefined;
  hostRuntime.activeForegroundInput = false;
  hostRuntime.controlledTargets = new Map<string, ControlledTarget>();
  hostRuntime.takeoverTargets = new Map<string, ControlledTarget>();
  hostRuntime.browserTargets = new Map<string, ControlledTarget>();
  hostRuntime.repliedConnections = new WeakSet<Socket>();
  hostRuntime.activeInputTaskKey = undefined;
  hostRuntime.monitoredTasks = new Map<string, string>();
  hostRuntime.inputInterruptCooldownUntil = 0;
  hostRuntime.inFlightInputInterrupts = new Set<AbortController>();
  hostRuntime.activeTaskCalls = new Map<AbortController, string>();
  hostRuntime.desktopPauses = new Set<string>();
  hostRuntime.desktopObservationRequired = false;
  hostRuntime.browserObservationRequired = false;
  hostRuntime.browserRecoveryObservations = new Map<string, number>();
  hostRuntime.desktopEpoch = 0;
  hostRuntime.desktopInterruptionCount = 0;
  hostRuntime.observedNativeRevision = undefined;
  hostRuntime.operations = Promise.resolve();
  hostRuntime.stopping = Promise.resolve();
  hostRuntime.cursorStyleUpdates = Promise.resolve();
  hostRuntime.epoch = 0;
  hostRuntime.inputMonitorEpochChanges = 0;
  hostRuntime.connections = new Set<Socket>();
  hostRuntime.permissions = undefined;
  hostRuntime.pendingPermissionChecks = new Map<() => void, string | undefined>();
  hostRuntime.userStoppedTasks = new Set<string>();
  hostRuntime.admittedTaskRequests = new Set<TaskRequest>();
  hostRuntime.knownTasks = new Map<string, CuaComputerTask>();
  hostRuntime.endedFrameTasks = new Set<string>();
  hostRuntime.frameTapTask = undefined;
  hostRuntime.warmAttempted = false;
  hostRuntime.options = options;

  return hostRuntime;
}
