import {
  Airplane01Icon,
  AudioLinesIcon,
  BackpackIcon,
  BookIcon,
  Brain03Icon,
  Briefcase06Icon,
  BriefcaseIcon,
  BugIcon,
  CalendarIcon,
  CameraIcon,
  ChartColumnIcon,
  ChartLineIcon,
  CloudIcon,
  CodeSquareIcon,
  Coffee03Icon,
  ComputerTerminal01Icon,
  DollarCircleIcon,
  DumbbellIcon,
  EarthIcon,
  EnergyIcon,
  FeatherIcon,
  FlaskConicalIcon,
  FlowerIcon,
  FolderIcon,
  GalaxyIcon,
  GameController03Icon,
  Globe02Icon,
  GraduationCapIcon,
  HammerIcon,
  HeartIcon,
  HeartPulseIcon,
  Home01Icon,
  LightbulbIcon,
  MessagesSquareIcon,
  Navigation05Icon,
  Notebook01Icon,
  PaletteIcon,
  PawPrintIcon,
  PencilEdit02Icon,
  PillIcon,
  PineTreeIcon,
  PopcornIcon,
  PuzzleIcon,
  Robot01Icon,
  Rocket01Icon,
  RulerIcon,
  ScaleIcon,
  SchoolIcon,
  ServerStack03Icon,
  ShoppingBagIcon,
  StarIcon,
  TargetIcon,
  TrophyIcon,
  UsersIcon,
  WrenchIcon,
} from "./icons";
import type { IconComponent, IconProps } from "./iconComponent";

// Project and space icon keys are persisted user data. Keep their names stable.
const ICONS: Readonly<Record<string, IconComponent>> = {
  airplane: Airplane01Icon,
  audio: AudioLinesIcon,
  backpack: BackpackIcon,
  bag: ShoppingBagIcon,
  "black-hole": GalaxyIcon,
  book: BookIcon,
  briefcase: Briefcase06Icon,
  "brackets-2": CodeSquareIcon,
  brain: Brain03Icon,
  bug: BugIcon,
  "calendar-1": CalendarIcon,
  "camera-1": CameraIcon,
  "chart-2": ChartColumnIcon,
  "chart-3": ChartLineIcon,
  "chat-bubbles": MessagesSquareIcon,
  cloud: CloudIcon,
  "code-brackets": CodeSquareIcon,
  "color-palette": PaletteIcon,
  console: ComputerTerminal01Icon,
  "cup-hot": Coffee03Icon,
  dollar: DollarCircleIcon,
  dumbell: DumbbellIcon,
  earth: EarthIcon,
  feather: FeatherIcon,
  "folder-2": FolderIcon,
  "form-flower": FlowerIcon,
  gamecontroller: GameController03Icon,
  globe: Globe02Icon,
  "graduate-cap": GraduationCapIcon,
  hammer: HammerIcon,
  heart: HeartIcon,
  "heart-beat": HeartPulseIcon,
  home: Home01Icon,
  lab: FlaskConicalIcon,
  law: ScaleIcon,
  "light-bulb": LightbulbIcon,
  lightning: EnergyIcon,
  maintenance: WrenchIcon,
  "map-pin": Navigation05Icon,
  "medicine-pill": PillIcon,
  notebook: Notebook01Icon,
  pencil: PencilEdit02Icon,
  people: UsersIcon,
  pets: PawPrintIcon,
  popcorn: PopcornIcon,
  puzzle: PuzzleIcon,
  robot: Robot01Icon,
  rocket: Rocket01Icon,
  ruler: RulerIcon,
  school: SchoolIcon,
  server: ServerStack03Icon,
  "shopping-bag-1": ShoppingBagIcon,
  star: StarIcon,
  "suitcase-work": BriefcaseIcon,
  target: TargetIcon,
  tree: PineTreeIcon,
  trophy: TrophyIcon,
};

export function NamedIcon({ name, ...props }: IconProps & { name: string }) {
  const Icon = ICONS[name];
  if (!Icon) throw new Error(`Unknown appearance icon key: ${name}`);
  return <Icon {...props} />;
}
