import {
  AstroAsoIcon,
  MobbinIcon,
  IntercomIcon,
  MiroIcon,
  GranolaIcon,
  DocusignIcon,
  SpotifyIcon,
  CalendlyIcon,
  UnityIcon,
  SuperhumanIcon,
  MercuryIcon,
  CraftIcon,
  BrowserUseIcon,
  MintlifyIcon,
  OpenStatusIcon,
  PolarIcon,
  ScalarIcon,
  AsideIcon,
  BetterStackIcon,
  ExecutorIcon,
  TldrawIcon,
  AmplitudeIcon,
  MixpanelIcon,
  GoogleAnalyticsIcon,
  ElevenLabsIcon,
  OnePasswordIcon,
  OpenRouterIcon,
  NeonIcon,
  MongoDBIcon,
  GrafanaIcon,
  AxiomIcon,
  PlanetScaleIcon,
  TursoIcon,
  ClerkIcon,
  PrismaIcon,
  ResendIcon,
  SanityIcon,
  GitLabIcon,
  AzureIcon,
  JetBrainsIcon,
  FirebaseIcon,
  NetlifyIcon,
  RenderIcon,
  RedisIcon,
  Auth0Icon,
  PerplexityIcon,
  AsanaIcon,
  TrelloIcon,
  DatabuddyIcon,
  UmamiIcon,
  FalAiIcon,
  UpstashIcon,
  ClickHouseIcon,
  TavilyIcon,
  ZapierIcon,
  Context7Icon,
  ExaIcon,
  BrowserbaseIcon,
  PenDevIcon,
  FirecrawlIcon,
  PlaywrightIcon,
  ChromeDevToolsIcon,
  SupabaseIcon,
  CloudflareIcon,
  AwsIcon,
  RailwayIcon,
  ConvexIcon,
  AtlassianIcon,
  SentryIcon,
  DatadogIcon,
  PostHogIcon,
  N8nIcon,
  BlenderIcon,
  PenpotIcon,
  DrawioIcon,
  ExcalidrawIcon,
  CalComIcon,
  ShopifyIcon,
  BraveSearchIcon,
  PaperIcon,
  CanvaIcon,
  FigmaIcon,
  GitHubIcon,
  GmailIcon,
  GoogleCalendarIcon,
  GoogleDriveIcon,
  HuggingFaceIcon,
  LinearIcon,
  NotionIcon,
  SlackIcon,
  StripeIcon,
  VercelIcon,
} from "~/lib/brandIcons";
import { Folder02Icon } from "./icons";
import type { IconComponent } from "./iconComponent";

export interface ServiceBrandArtwork {
  color: string;
  icon: IconComponent;
}
const SERVICE_BRANDS: Record<string, ServiceBrandArtwork> = {
  canva: {
    icon: CanvaIcon,
    color: "#00C4CC",
  },
  figma: {
    icon: FigmaIcon,
    color: "#F24E1E",
  },
  github: {
    icon: GitHubIcon,
    color: "#181717",
  },
  gmail: {
    icon: GmailIcon,
    color: "#EA4335",
  },
  googlecalendar: {
    icon: GoogleCalendarIcon,
    color: "#4285F4",
  },
  googledrive: {
    icon: GoogleDriveIcon,
    color: "#0F9D58",
  },
  huggingface: {
    icon: HuggingFaceIcon,
    color: "#FF9D00",
  },
  linear: {
    icon: LinearIcon,
    color: "#5E6AD2",
  },
  notion: {
    icon: NotionIcon,
    color: "#111111",
  },
  slack: {
    icon: SlackIcon,
    color: "#4A154B",
  },
  stripe: {
    icon: StripeIcon,
    color: "#635BFF",
  },
  vercel: {
    icon: VercelIcon,
    color: "#111111",
  },
  context7: { icon: Context7Icon, color: "#687080" },
  exa: { icon: ExaIcon, color: "#687080" },
  browserbase: { icon: BrowserbaseIcon, color: "#687080" },
  pendev: { icon: PenDevIcon, color: "#687080" },
  firecrawl: { icon: FirecrawlIcon, color: "#687080" },
  playwright: { icon: PlaywrightIcon, color: "#687080" },
  chromedevtools: { icon: ChromeDevToolsIcon, color: "#687080" },
  supabase: { icon: SupabaseIcon, color: "#687080" },
  cloudflare: { icon: CloudflareIcon, color: "#687080" },
  aws: { icon: AwsIcon, color: "#687080" },
  railway: { icon: RailwayIcon, color: "#687080" },
  convex: { icon: ConvexIcon, color: "#687080" },
  atlassian: { icon: AtlassianIcon, color: "#687080" },
  sentry: { icon: SentryIcon, color: "#687080" },
  datadog: { icon: DatadogIcon, color: "#687080" },
  posthog: { icon: PostHogIcon, color: "#687080" },
  n8n: { icon: N8nIcon, color: "#687080" },
  blender: { icon: BlenderIcon, color: "#687080" },
  penpot: { icon: PenpotIcon, color: "#687080" },
  drawio: { icon: DrawioIcon, color: "#687080" },
  excalidraw: { icon: ExcalidrawIcon, color: "#687080" },
  calcom: { icon: CalComIcon, color: "#687080" },
  shopify: { icon: ShopifyIcon, color: "#687080" },
  bravesearch: { icon: BraveSearchIcon, color: "#687080" },
  paper: { icon: PaperIcon, color: "#687080" },
  neon: { icon: NeonIcon, color: "#687080" },
  mongodb: { icon: MongoDBIcon, color: "#687080" },
  grafana: { icon: GrafanaIcon, color: "#687080" },
  axiom: { icon: AxiomIcon, color: "#687080" },
  planetscale: { icon: PlanetScaleIcon, color: "#687080" },
  turso: { icon: TursoIcon, color: "#687080" },
  clerk: { icon: ClerkIcon, color: "#687080" },
  prisma: { icon: PrismaIcon, color: "#687080" },
  resend: { icon: ResendIcon, color: "#687080" },
  sanity: { icon: SanityIcon, color: "#687080" },
  gitlab: { icon: GitLabIcon, color: "#687080" },
  azure: { icon: AzureIcon, color: "#687080" },
  jetbrains: { icon: JetBrainsIcon, color: "#687080" },
  firebase: { icon: FirebaseIcon, color: "#687080" },
  netlify: { icon: NetlifyIcon, color: "#687080" },
  render: { icon: RenderIcon, color: "#687080" },
  redis: { icon: RedisIcon, color: "#687080" },
  auth0: { icon: Auth0Icon, color: "#687080" },
  perplexity: { icon: PerplexityIcon, color: "#687080" },
  asana: { icon: AsanaIcon, color: "#687080" },
  trello: { icon: TrelloIcon, color: "#687080" },
  databuddy: { icon: DatabuddyIcon, color: "#687080" },
  umami: { icon: UmamiIcon, color: "#687080" },
  falai: { icon: FalAiIcon, color: "#687080" },
  upstash: { icon: UpstashIcon, color: "#687080" },
  clickhouse: { icon: ClickHouseIcon, color: "#687080" },
  tavily: { icon: TavilyIcon, color: "#687080" },
  zapier: { icon: ZapierIcon, color: "#687080" },
  elevenlabs: { icon: ElevenLabsIcon, color: "#687080" },
  "1password": { icon: OnePasswordIcon, color: "#687080" },
  openrouter: { icon: OpenRouterIcon, color: "#687080" },
  tldraw: { icon: TldrawIcon, color: "#687080" },
  amplitude: { icon: AmplitudeIcon, color: "#687080" },
  mixpanel: { icon: MixpanelIcon, color: "#687080" },
  googleanalytics: { icon: GoogleAnalyticsIcon, color: "#687080" },
  filesystem: { icon: Folder02Icon, color: "#687080" },
  intercom: { icon: IntercomIcon, color: "#687080" },
  miro: { icon: MiroIcon, color: "#687080" },
  granola: { icon: GranolaIcon, color: "#687080" },
  docusign: { icon: DocusignIcon, color: "#687080" },
  spotify: { icon: SpotifyIcon, color: "#687080" },
  calendly: { icon: CalendlyIcon, color: "#687080" },
  unity: { icon: UnityIcon, color: "#687080" },
  superhuman: { icon: SuperhumanIcon, color: "#687080" },
  mercury: { icon: MercuryIcon, color: "#687080" },
  craft: { icon: CraftIcon, color: "#687080" },
  browseruse: { icon: BrowserUseIcon, color: "#687080" },
  mintlify: { icon: MintlifyIcon, color: "#687080" },
  openstatus: { icon: OpenStatusIcon, color: "#687080" },
  polar: { icon: PolarIcon, color: "#687080" },
  scalar: { icon: ScalarIcon, color: "#687080" },
  aside: { icon: AsideIcon, color: "#687080" },
  betterstack: { icon: BetterStackIcon, color: "#687080" },
  executor: { icon: ExecutorIcon, color: "#687080" },
  astroaso: { icon: AstroAsoIcon, color: "#687080" },
  mobbin: { icon: MobbinIcon, color: "#687080" },
};
const SERVICE_ALIASES: Record<string, string> = {
  cf: "cloudflare",
  awsdocumentation: "aws",
  chrome: "chromedevtools",
  cal: "calcom",
  diagramsnet: "drawio",
  brave: "bravesearch",
  pencil: "pendev",
  pen: "pendev",
  context7mcp: "context7",
  firecrawlmcp: "firecrawl",
  playwrightmcp: "playwright",
  chromedevtoolsmcp: "chromedevtools",
  browserbasemcp: "browserbase",
  mcpserverbravesearch: "bravesearch",
  supabasemcp: "supabase",
  mcpatlassian: "atlassian",
  paperdesktop: "paper",
  tursodb: "turso",
  fal: "falai",
  azuredevops: "azure",
  azuremcpserver: "azure",
  azdevops: "azure",
  mongodbmcpserver: "mongodb",
  mongodbatlasmcpremote: "mongodb",
  firebasemcpserver: "firebase",
  upstashredis: "upstash",
  planetscaleinsightsonly: "planetscale",
  onepassword: "1password",
  "1pass": "1password",
  elevenlabsmcp: "elevenlabs",
  openroutermcp: "openrouter",
  ga4: "googleanalytics",
  analyticsmcp: "googleanalytics",
  googleanalyticsmcp: "googleanalytics",
  serverfilesystem: "filesystem",
  tldrawlocal: "tldraw",
  mirocom: "miro",
  craftdo: "craft",
  superhumanmail: "superhuman",
  polarsh: "polar",
  polarsandbox: "polar",
  asidecom: "aside",
  executorsh: "executor",
  astro: "astroaso",
  tryastro: "astroaso",
  tryastroapp: "astroaso",
  browserharnessmcp: "browseruse",
};
export function resolveServiceBrand(
  value: string | null | undefined,
): ServiceBrandArtwork | undefined {
  const key = (value ?? "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "");
  return SERVICE_BRANDS[SERVICE_ALIASES[key] ?? key];
}
